### ISSUE TITLE
Error when starting the plateViewer

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-plateViewer#28]
I get the following error when I try to open the plate viewer with one of the folders processed by batchlib. I am using the latest version in Fiji.

![Screenshot from 2020-05-10 20-46-07](https://user-images.githubusercontent.com/4263537/81507697-62324980-92ff-11ea-9051-7759e8907cca.png)

**Comment by tischi** [comment]
1. Which plate was it?
2. If you uncheck the well and image table loading, does it still happen?

**Comment by constantinpape** [comment]
> * Which plate was it?

This was just for the small test sample I get for this data:
https://github.com/hci-unihd/batchlib/tree/master/data/test_data/test

> 
> * If you uncheck the well and image table loading, does it still happen?

It only happens for the well table (loading not table works and also loading just the image table works).

Maybe it's due to the changes I made to the table columns yesterday.
If so, you can check if it works for any of these plates:
`/g/kreshuk/data/covid/sandbox/for_tischi`

They have been written with the latest version. I don't have time to check them right now, I can do it later.

**Comment by tischi** [comment]
For me it works => some nasty multi-threading issues.
I released a new version, hopefully more thread-safe...

**Comment by constantinpape** [comment]
Ok, I will test it later

**Comment by constantinpape** [comment]
Still the same issue.
I will zip the folder later and upload it somewhere.
Also, @wolny mentioned he saw something similar.

**Comment by constantinpape** [comment]
Ok, nvmd @wolny's issue is only related to the issue reporting.

**Comment by constantinpape** [comment]
https://oc.embl.de/index.php/s/PGZRHc8dGSVrQZs

**Comment by tischi** [comment]
Thanks for reporting and providing the example.
My scatter plot code was crashing if there is only one data point, which was the case for the wells in this example.

I simply capture this now, because having a scatter plot for only one data point seems not to be too useful anyway...

```
fetchDataPoints( columnNameX, columnNameY );

if ( points.size() < 2 )
{
	throw new UnsupportedOperationException( "Cannot create scatter plot \"" + name + "\", because there are less than two valid data points." );
}
```
